TruckManager/Models/ErrorViewModel.cs
using System;

namespace TruckManager.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TruckManager/Models/Truck.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using TruckManager.Infrastructure;

namespace TruckManager.Models
{
    [Index(nameof(Name), IsUnique = true)]
    public class Truck : IEntity
    {
        public Guid Id { get; set; }

        [Required, Display(Name = "Name"), StringLength(50)]
        public string Name { get; set; }

        [Required, Display(Name = "Model")]
        public TruckModel Model { get; set; }

        [Required, Display(Name = "Manufacturing year")]
        public int ManufacturingYear { get; set; }

        [Required, Display(Name = "Model year")]
        public int ModelYear { get; set; }
    }
}

TruckManager/Models/TruckModel.cs
using System.ComponentModel.DataAnnotations;

namespace TruckManager.Models
{
    public enum TruckModel
    {
        [Display(Name = "Frontal high")]
        FrontalHigh = 1,

        [Display(Name = "Frontal medium")]
        FrontalMedium = 2
    }
}

TruckManager/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using TruckManager.Models;

namespace TruckManager.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TruckManager/Controllers/TrucksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using TruckManager.Infrastructure;
using TruckManager.Models;
using TruckManager.Services;

namespace TruckManager.Controllers
{
    [Authorize]
    public class TrucksController : Controller
    {
        private readonly ITruckService _service;

        public TrucksController(ITruckService service)
        {
            _service = service;
        }

        // GET: Trucks
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAll());
        }

        // GET: Trucks/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var truck = await _service.Get(id.Value);

            if (truck == null)
            {
                return NotFound();
            }

            return View(truck);
        }

        // GET: Trucks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trucks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Model,ManufacturingYear,ModelYear")] Truck truck)
        {
            if (ModelState.IsValid)
            {
                var result = await _service.Add(truck);

                if (!result.ValidationErrors.Any())
                {
                    return RedirectToAction(nameof(Index));
                }

                foreach (var error in result.ValidationErrors)
                {
                    ModelState.AddModelError(error.Key, error.Value);
                }
            }

            return View(truck);
        }

        // GET: Trucks/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var truck = await _service.Get(id.Value);

            if (truck == null)
            {
                return NotFound();
            }

            return View(truck);
        }

        // POST: Trucks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Model,ManufacturingYear,ModelYear")] Truck truck)
        {
            if (id != truck.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                ServiceResult<Truck> result;

                try
                {
                    result = await _service.Update(truck);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_service.TruckExists(truck.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                if (!result.ValidationErrors.Any())
                {
                    return RedirectToAction(nameof(Index));
                }

                foreach (var error in result.ValidationErrors)
                {
                    ModelState.AddModelError(error.Key, error.Value);
                }
            }

            return View(truck);
        }

        // GET: Trucks/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var truck = await _service.Get(id.Value);

            if (truck == null)
            {
                return NotFound();
            }

            return View(truck);
        }

        // POST: Trucks/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            var truck = await _service.Delete(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

TruckManager/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Go to the <a asp-controller="Trucks" asp-action="Index">truck listing</a> page.</p>
</div>

TruckManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TruckManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TruckManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TruckManager
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TruckManager/Views/Trucks/Create.cshtml
@model TruckManager.Models.Truck

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Truck</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <select asp-for="Model" class="form-control" asp-items="Html.GetEnumSelectList<TruckModel>()">
                    <option selected="selected" value="">---Please select---</option>
                </select>
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturingYear" class="control-label"></label>
                <input asp-for="ManufacturingYear" class="form-control" value="@DateTime.Now.Year" readonly="readonly" />
                <span asp-validation-for="ManufacturingYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelYear" class="control-label"></label>
                <select asp-for="ModelYear" class="form-control">
                    <option selected="selected" value="@DateTime.Now.Year">@DateTime.Now.Year</option>
                    <option value="@(DateTime.Now.Year + 1)">@(DateTime.Now.Year + 1)</option>
                </select>
                <span asp-validation-for="ModelYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TruckManager/Views/Trucks/Delete.cshtml
@model TruckManager.Models.Truck

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Truck</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.ManufacturingYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturingYear)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModelYear)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TruckManager/Views/Trucks/Details.cshtml
@model TruckManager.Models.Truck

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Truck</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.ManufacturingYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturingYear)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModelYear)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TruckManager/Views/Trucks/Edit.cshtml
@model TruckManager.Models.Truck

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Truck</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" readonly="readonly" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <select asp-for="Model" class="form-control" asp-items="Html.GetEnumSelectList<TruckModel>()"></select>
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturingYear" class="control-label"></label>
                <input asp-for="ManufacturingYear" class="form-control" />
                <span asp-validation-for="ManufacturingYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelYear" class="control-label"></label>
                <input asp-for="ModelYear" class="form-control" />
                <span asp-validation-for="ModelYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TruckManager/Views/Trucks/Index.cshtml
@model IEnumerable<TruckManager.Models.Truck>

@{
    ViewData["Title"] = "Index";
}

<h1>Truck list</h1>

<p>
    <a asp-action="Create">Create new</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManufacturingYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModelYear)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ManufacturingYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModelYear)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>